# Generated by Django 5.2.8 on 2025-11-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('ProductID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('SI_NO', models.IntegerField(max_length=15)),
                ('Product_Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=60)),
                ('Price', models.IntegerField(max_length=5)),
                ('Weight', models.IntegerField(max_length=5)),
                ('Stock_state', models.CharField(max_length=20)),
            ],
        ),
    ]
