# Generated by Django 5.2.8 on 2025-11-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='SI_NO',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Weight',
            field=models.IntegerField(),
        ),
    ]
